Settings:
  InfiniteJump: false
  Launch_power: 1.0
  Launch_power_y: 0.5
  Sound: "ENTITY_BAT_TAKEOFF"
  SoundError: "ENTITY_VILLAGER_NO"
Messages:
  DoubleJump: "&dYou jumped twice :)"
  AlreadyDoubleJumped: "&cYou Already DoubleJumped Before"
  DoubleJumpIsActive: "&aNow You Can DoubleJump Again"