# Don't Change ConfigVersion !!!
ConfigVersion: 1.0

Settings:
  # Should the player be able to jump infinitely?
  InfiniteJump: false
  # Launch power for double jump (max 10)
  Launch: 1.0
  LaunchY: 0.5

Actions:
  # The prefix that will appear at the beginning of all messages, set "" to disable
  prefix: "&dBDJ &6> "
  # Actions That Will Run When Player Jumps
  OnJump:
    # Message sent after the jump, set "" to disable
    message: "&bYou jumped twice :)"
    # The sound that plays after jump, set "" to disable
    # List Of Sounds https://helpch.at/docs/1.12/index.html?org/bukkit/Sound.html
    sound: "ENTITY_BAT_TAKEOFF"
    # Run Command For Player When Jump, set "" to disable
    command: ""
  OnActive:
    # message sent when the player lands after jump, set "" to disable
    message: "&bNow You Can DoubleJump Again"
  Errors:
    AlreadyJumped:
      # Message sent when player can't jump again, set "" to disable
      message: "&bYou Already DoubleJumped Before"
      # The sound that plays when player can't jump again, set "" to disable
      sound: "ENTITY_VILLAGER_NO"