# Don't Change ConfigVersion !!!
ConfigVersion: 1.0

Settings:
  # Allow players to jump infinitely? (true/false)
  InfiniteJump: false
  # Horizontal launch power (max 10)
  Launch: 1.0
  # Vertical launch power (Y axis)
  LaunchY: 0.5

Actions:
  # The prefix that will appear at the beginning of all messages (set "" to disable)
  prefix: "&dBDJ &6> "
  # Actions that will run when player jumps
  OnJump:
    # Message sent after the jump (set "" to disable)
    message: "&bYou jumped twice :)"
    # The sound that plays after the jump (set "" to disable)
    # List Of Sounds https://helpch.at/docs/1.12/index.html?org/bukkit/Sound.html
    sound: "ENTITY_BAT_TAKEOFF"
    # The command that runs after jump (set "" to disable)
    command: ""
  OnActive:
    # Message sent when the player lands after jump (set "" to disable)
    message: "&bNow You Can DoubleJump Again"
  Errors:
    AlreadyJumped:
      # Message sent when the player can't jump again (set "" to disable)
      message: "&bYou Already DoubleJumped Before"
      # The sound that plays when the player can't jump again (set "" to disable)
      sound: "ENTITY_VILLAGER_NO"
    Cooldown:
      message: ""
      sound: ""
    NotAvailable:
      message: ""
      sound: ""