name: BlazeyDoubleJump
version: '${version}'
main: me.vesder.blazeydoublejump.BlazeyDoubleJump
api-version: "1.13"
authors: [ vesder ]
description: A simple double jump plugin for bukkit servers
softdepend:
  - Vault
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI
commands:
  blazeydoublejump:
    description: Plugin main command
    usage: /<command>
    aliases:
      - bdoublejump
      - bdj
    permission: blazeydoublejump.command
    permission-message: You do not have permission to use this command.

permissions:
  blazeydoublejump.admin:
    description: Grants full administrative access to all BlazeyDoubleJump commands and settings.
    default: op
    children:
      blazeydoublejump.command.help: true
      blazeydoublejump.command.reload: true
      blazeydoublejump.command.settings: true
      blazeydoublejump.command.actions: true
  blazeydoublejump.doublejump:
    description: Allows the player to use the double jump ability.
    default: true
  blazeydoublejump.infinitejump:
    description: Allows the player to perform unlimited double jumps.
    default: op
  blazeydoublejump.command.settings:
    description: Allows use of /bdj settings to change plugin options.
    default: op